# COMPUTACIÓN BLANDA - Sistemas y Computación - Machine Learning 1
-------------------------------------------
# Introducción a numpy
### Presentado por: Juan Jose Leon Tabares Cc: 1225092968
-------------------------------------------
Lección 01

Creación de arrays
Acceso a los arrays
Manejo de rangos
Modificación de arrays



In [5]:
# Se importa la librería numpy
import numpy as np

# Se crea una array con 6 elementos
a = np.arange(11)

# Se imprime en pantalla el contenido del array a
print('Arreglo a =', a, '\n')

# Se muestra el tipo de los elementos del array
print('Tipo de a =', a.dtype, '\n')

# Se calcula la dimensión del array a, en este caso dimensión = 1 (vector)
print('Dimensión de a =', a.ndim, '\n')

# Se calcula el número de elementos del array a
# No olvidar que existe un elemento con índice 0
print('Número de elementos de a =', a.shape)

Arreglo a = [ 0  1  2  3  4  5  6  7  8  9 10] 

Tipo de a = int32 

Dimensión de a = 1 

Número de elementos de a = (11,)


In [6]:
# Creando un arreglo multidimensional
# La matriz se crea con la función: array
# La matriz debe de ser de las mismas dimensiones en X
m = np.array([np.arange(3), np.arange(3)])
print(m)

[[0 1 2]
 [0 1 2]]


In [20]:
# Seleccionando elementos de un array

a = np.array([[1,2,3], [4,5,6,]])
print('a =\n', a, '\n')
# Elementos individuales
print('a[0,0] =', a[0,0], '\n')
print('a[0,1] =', a[0,1], '\n')
print('a[0,2] =', a[0,2], '\n')
print('a[1,0] =', a[1,0], '\n')
print('a[1,1] =', a[1,1], '\n')
print('a[1,2] =', a[1,2])

a =
 [[1 2 3]
 [4 5 6]] 

a[0,0] = 1 

a[0,1] = 2 

a[0,2] = 3 

a[1,0] = 4 

a[1,1] = 5 

a[1,2] = 6


In [7]:
# Crea un array con 11 elementos, desde 0 hasta 10

a = np.arange(11)

print('a =', a, '\n')

# Muestra los elementos desde 0 hasta 11. Imprime desde 0 hasta 10
print('a[0:11] = ', a[0:11], '\n')

# Muestra desde 3 hasta 7. Imprime desde 3 hasta 6
print('a[3,8] =', a[3:8])

a = [ 0  1  2  3  4  5  6  7  8  9 10] 

a[0:11] =  [ 0  1  2  3  4  5  6  7  8  9 10] 

a[3,8] = [3 4 5 6 7]


In [30]:
# Mostrando todos los elementos, desde el 0 hasta el 8, de uno en uno
print('a[0:11:1] =', a[0:11:1], '\n')

# El mismo ejemplo, pero omitiendo el número 0 al principio, el cual no es necesario aquí
print('a[:11:1] =', a[:11:1], '\n')

# Mostrando los números, de dos en dos
print('a[0:11:2] =', a[0:11:2], '\n')

# Mostrando los números, de tres en tres
print('a[0:11:3] =', a[0:11:3], '\n')

# Mostrando los números, de cuatro en cuatro
print('a[0:11:4] =', a[0:11:4])

a[0:11:1] = [ 0  1  2  3  4  5  6  7  8  9 10] 

a[:11:1] = [ 0  1  2  3  4  5  6  7  8  9 10] 

a[0:11:2] = [ 0  2  4  6  8 10] 

a[0:11:3] = [0 3 6 9] 

a[0:11:4] = [0 4 8]


In [8]:
# Si utilizamos un incremento negativo, el array se muestra en orden inverso

# El problema es que no muestra el valor 0
print('a[11:0:-1] =', a[11:0:-1], '\n')

# Si se omiten los valores de índice, el resultado es preciso
print('a[::-1] =', a[::-1])

a[11:0:-1] = [10  9  8  7  6  5  4  3  2  1] 

a[::-1] = [10  9  8  7  6  5  4  3  2  1  0]


# Utilizacion de arreglos multidimensionales

In [9]:

b = np.arange(30).reshape(2,3,5)
print('b =\n', b)
# La instrucción reshape genera una matriz con 2 bloques, 3 filas y 4 columnas
# El número total de elementos es de 24 (generados por arange)

b =
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [12]:
# Acceso individual a los elementos del array

# Elemento en el bloque 1, fila 2, columna 3
print('b[1,2,3] =', b[1,2,3], '\n')

# Elemento en el bloque 0, fila 2, columna 2
print('b[0,2,2] =', b[0,2,2], '\n')

# Elemento en el bloque 1, fila 1, columna 1
print('b[1,1,1] =', b[1,1,1], '\n')

# Elemento en el bloque 0, fila 2, columna 1
print('b[0,2,1] =', b[0,2,1])

b[1,2,3] = 28 

b[0,2,2] = 12 

b[1,1,1] = 21 

b[0,2,1] = 11


In [18]:
# Mostraremos como generalizar una selección

# Primero elegimos el componente en el bloque 0, fila 0, columna 0
print('b[0,0,0] =', b[0,0,0], '\n')

# A continuación, elegimos el componente en el bloque 1, fila 0, columna 0
print('b[1,0,0] =', b[1,0,0], '\n')

# Para elegir SIMULTANEAMENTE ambos elementos del bloque, lo hacemos utilizando dos puntos
print('b[:,0,0] =', b[:,0,0], '\n')

# Para elegir simultaneamente los elementos del bloque 0 y columnaa 0
print('b[0,:,0] =', b[0,:,0], '\n')

# Para elegir simultaneamente los elementos del bloque o y 1,  columnaa 0
print('b[:,:,0] =', b[:,:,0], '\n')

# Para elegir simultaneamente los elementos del bloque 0 y fila 1
print('b[:,0,0] =', b[0,1,:], '\n')

b[0,0,0] = 0 

b[1,0,0] = 15 

b[:,0,0] = [ 0 15] 

b[0,:,0] = [ 0  5 10] 

b[:,:,0] = [[ 0  5 10]
 [15 20 25]] 

b[:,0,0] = [5 6 7 8 9] 



In [21]:
# Si escribimos: b[1]

# Habremos elegido el primer bloque, pero habríamos omitido las filas y las columnas
# En tal caso, numpy toma todas las filas y columnas del bloque 1
print('b[1] =\n', b[1])

b[1] =
 [[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [23]:
# Otra forma de representar b[1] es: b[1, :, :]

# Los dos puntos sin ningún valor, indican que se utilizarán todos los términos disponibles
# En este caso, todas las filas y todas las columnas
print('b[1,:,:] =\n', b[1,:,:])

b[1,:,:] =
 [[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [26]:
# Cuando se utiliza la notación de : a derecha o a izquierda, se puede reemplazar por ...
# El ejemplo anterior se puede escribir así:
print('b[1, ...] =\n', b[1, ...])

b[1, ...] =
 [[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [27]:
# Si queremos la fila 1 en el bloque 0 (sin que importen las columnas), se tiene:
print('b[0,1] =', b[0,1])

b[0,1] = [5 6 7 8 9]


In [56]:
# El resultado de una selección se puede utilizar luego para un cálculo posterior

# Se obtiene la fila 1 del bloque 0 (como en ejemplo anterior)
# y se asigna dicha respuesta a la variable z
z = b[0,1]
print('z =', z, '\n')

# En este caso, la variable z toma el valor: [ 5 6 7 8 9]
# Si ahora queremos tomar de dicha respuesta los valores de 2 en 2, se tiene:
print('z[::2] =', z[::2], '\n') 

# Si ahora queremos tomar de dicha respuesta los valores invertidos, se tiene:
print('z[::-1] =', z[::-1], '\n') 

z = [5 6 7 8 9] 

z[::2] = [5 7 9] 

z[::-1] = [9 8 7 6 5] 



In [59]:
# El ejercicio anterior se puede combinar en una expresión única, así:
# Se toma el bloque 0 y la fila 1 de saltos de 2
print('b[0,1,::2] =', b[0,1,::2])
# Esta es una solución más compacta

b[0,1,::2] = [5 7 9]


In [65]:
# Imprime todas las columnas, independientemente de los bloques y filas

print('b=',b, '\n')
print('b[:,:,1] =\n', b[:,:,2], '\n')

# Variante de notación (simplificada)
print('b[...,1] =\n', b[...,2])

b= [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 

b[:,:,1] =
 [[ 2  7 12]
 [17 22 27]] 

b[...,1] =
 [[ 2  7 12]
 [17 22 27]]


In [64]:
# Si queremos seleccionar todas las filas 2, independientemente

# de los bloques y columnas, se tiene:
print('b=',b, '\n')
print('b[:,1] =', b[:,1])
# Puesto que no se menciona en la notación las columnas, se toman todos
# los valores según corresponda

b= [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 

b[:,1] = [[ 5  6  7  8  9]
 [20 21 22 23 24]]


In [70]:
# En el siguiente ejemplo seleccionmos la columna 1 del bloque 0

print('b=',b, '\n')
print('b[0,:,1] =', b[0,:,1],'\n')

# En el siguiente ejemplo seleccionmos la columna 1 del bloque 1
print('b[1,:,1] =', b[1,:,1])

b= [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 

b[0,:,1] = [ 1  6 11] 

b[1,:,1] = [16 21 26]


In [76]:
# Si queremos seleccionar la última columna del primer bloque, tenemos:

print('b[0,:,-1] =', b[0,:,-1])

# Podemos observar lo siguiente: entre corchetes encontramos tres valores
# El primero, el cero, selecciona el primer bloque
# El tercero, -1, se encarga de seleccionar la última columna
# Los dos puntos, en la segunda posición, SELECCIONAN todos los
# componentes de lad FILAS, que FORMARÁN PARTE de dicha COLUMNA
# Dado que los dos puntos definen todos los valores de las FILAS en
# una columna específica, si quisieramos que DICHOS VALORES estuvieran
# en orden inverso, ejecutaríamos la instrucción
print('b[0, ::-1, -1] =', b[0, ::-1, -1])
# La expresión ::-1 invierte todos los valores que se hubieran seleccionado
# Si en lugar de invertir la columna, quisieramos imprimir sus
# valores de 2 en 2, tendríamos:
print('b[0, ::2, -1] =', b[0, ::2, -1])

b[0,:,-1] = [ 4  9 14]
b[0, ::-1, -1] = [14  9  4]
b[0, ::2, -1] = [ 4 14]


In [77]:
# El array original

print(b, '\n-----------------------\n')
# Esta instrucción invierte los bloques
print(b[::-1])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 
-----------------------

[[[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]


In [78]:
# La instrucción: ravel(), de-construye el efecto de la instrucción: reshape, lo vuelve en el vector o estado original

# Este es el array b en su estado matricial
print('Matriz b =\n', b, '\n--------------------------\n')
# Con ravel() se genera un vector a partir de la matriz
print('Vector b = \n', b.ravel())

Matriz b =
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 
--------------------------

Vector b = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [79]:
# La instrucción: flatten() es similar a ravel()

# La diferencia es que flatten genera un nuevo espacio de memoria
print('Vector b con flatten =\n', b.flatten())

Vector b con flatten =
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [85]:
# Se puede cambiar la estructura de una matriz con la instrucción: shape

# Transformamos la matriz en 3 filas x 10 columnas
b.shape = (3,10)
print('b(3x10) =\n', b)

b(3x10) =
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [86]:
# A partir de la matriz que acaba de ser generada, vamos a mostrar

# como se construye la transpuesta de la matriz
# Matriz original
print('b =\n', b, '\n------------------------\n')
# Matri transpuesta
print('Transpuesta de b =\n', b.transpose(), '\n------------------------\n')

b =
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] 
------------------------

Transpuesta de b =
 [[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]] 
------------------------



In [88]:
# Para concluir este primer módulo de numpy, mostraremos que la instrucción

# resize, ejecuta una labor similar a reshape
# La diferencia está en que resize altera la estructura del array
# En cambio reshape crea una copia del original, razón por la cual en
# reshape se debe asignar el resultado a una nueva variable
# Se cambia la estructura del array b
b.resize([3,10])
# Al imprimir el array b, se observa que su estructura ha cambiado
print('b =\n', b)

b =
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
