# PROCESAMIENTO DIGITAL

# COMPUTACION BLANDA 

# Taller validación Regresión y Clasificación

# Presentado por: Juan Jose Leon Tabares

In [3]:
# Se importan las librería numpy y las funciones de preprocesamiento
import numpy as np
from sklearn import preprocessing

# Datos de prueba
input_data = np.array(
[[5.5, -3.9, 0.3],
[-2.2, 3.8, -6.5],
[9.5, 0.4, 4.1],
[7.5, -9.9, -5.5]])

print(input_data)

[[ 5.5 -3.9  0.3]
 [-2.2  3.8 -6.5]
 [ 9.5  0.4  4.1]
 [ 7.5 -9.9 -5.5]]


In [5]:
# Binarizar los datos

data_binarized = preprocessing.Binarizer(threshold=0).transform(input_data)
print("\nDatos binarizados:\n", data_binarized)


Datos binarizados:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 1. 1.]
 [1. 0. 0.]]


In [11]:
# Imprimir la media y la desviación estándar

print("\nANTES:")
# Con axis = 0 --> saca la media de cada columna de la matriz
# Con axix = 1 --> saca la media de cada fila de la matriz
print("Media =", input_data.mean(axis=0))
print("Desviación estándar =", input_data.std(axis=0))


ANTES:
Media = [ 5.075 -2.4   -1.9  ]
Desviación estándar = [4.4319155  5.11810512 4.32897216]


In [12]:
# Remover la media

data_scaled = preprocessing.scale(input_data)
print("\nDESPUÉS:")
print("Media =", data_scaled.mean(axis=0))
print("Desviación estándar =", data_scaled.std(axis=0))


DESPUÉS:
Media = [-5.55111512e-17 -5.55111512e-17  1.11022302e-16]
Desviación estándar = [1. 1. 1.]


In [13]:
# Escalamiento Min Max

data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMin max escalamiento de datos:\n", data_scaled_minmax)


Min max escalamiento de datos:
 [[0.65811966 0.4379562  0.64150943]
 [0.         1.         0.        ]
 [1.         0.75182482 1.        ]
 [0.82905983 0.         0.09433962]]


In [14]:
# Normalización de datos

data_normalized_l1 = preprocessing.normalize(input_data,norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data,norm='l2')
print("\nL1 dato normalizado:\n", data_normalized_l1)
print("\nL2 dato normalizado:\n", data_normalized_l2)


L1 dato normalizado:
 [[ 0.56701031 -0.40206186  0.03092784]
 [-0.176       0.304      -0.52      ]
 [ 0.67857143  0.02857143  0.29285714]
 [ 0.32751092 -0.43231441 -0.24017467]]

L2 dato normalizado:
 [[ 0.81492661 -0.57785705  0.04445054]
 [-0.28046536  0.48444016 -0.82864764]
 [ 0.91745697  0.03862977  0.39595511]
 [ 0.55214267 -0.72882832 -0.40490462]]


In [24]:
# Manejo de etiquetas

import numpy as np
from sklearn import preprocessing

# Se definen algunas etiquetas simples
input_labels = ['red', 'black', 'red', 'green', 'black', 'yellow','white']

# Se crea un codificador de etiquetas y se ajustan las etiquetas
encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)

# Se imprime el mapeo entre palabras y números
print("\nMapeo de etiquetas:")
for i, item in enumerate(encoder.classes_):
    print(item, "-->", i)

# Codificar un conjunto de etiquetas con el codificador
test_labels = ['green', 'red', 'yellow','black']
encoded_values = encoder.transform(test_labels)
print("\nLabels =", test_labels)
print("Encoded values =", list(encoded_values))

# Decodificar un conjunto de valores usando el codificador
encoded_values = [3, 0, 4, 1,0]
decoded_list = encoder.inverse_transform(encoded_values)
print("\nEncoded values =", encoded_values)
print("Decoded labels =", list(decoded_list))


Mapeo de etiquetas:
black --> 0
green --> 1
red --> 2
white --> 3
yellow --> 4

Labels = ['green', 'red', 'yellow', 'black']
Encoded values = [1, 2, 4, 0]

Encoded values = [3, 0, 4, 1, 0]
Decoded labels = ['white', 'black', 'yellow', 'green', 'black']
